### ISSUE TITLE
Dashboard Needs Love

### ISSUE THREAD

**Issue by ColinW520** [ColinW520/hydra#14]
The dashboard needs to be simple, and display the most pertinent, relevant data summaries.

**Comment by ColinW520** [comment]
@browning25 -- I need your brain power on this. What should our dashboard look like? What is the most relevant, important, thing users want to see? Here are some options:

- Messaging Volume
  - In vs Out, Total, etc
- Calls Logged 
  - if they have any lines doing call logging forwarding?
- _Usage_
  - what Twilio is billing them for
  - we could do charts, or a table, or just lists?
- Logins
  - when did team users last log in?
- Recent messages 
  - a panel showing the most recent messages received

**Comment by browning25** [comment]
I think the biggest things I would want to see are: 
- Cost (what Twilio is billing them for each month, broken out by line)
- Notification of how many messages were sent and received since the last login for each line
- Graph of total number of messages sent and received for the month (broken out by line)

                                                        August 2017
                      Line 1                                                                Line 2                                                   
Cost: $1.27                                                                 Cost: $10.75
New Inbound Messages: 4                                        New Inbound Messages: 56
New Sent Messages: 10                                            New Sent Messages: 230

Graph of total messages sent for the month           Graph of total messages sent for the month

**Comment by browning25** [comment]
@ColinW520 -- suggest we close this issue for now. I think the appropriate information is being displayed.  It could always be re-formatted, but that is something we should worry about later.

**Comment by ColinW520** [comment]
@browning25 agreed! PUNTING
